##
## Read:
## https://github.com/codemeistre/.github/blob/main/.github/workflows/auto_close_issues_and_pull_requests.yml
##

name: Close issues and pull request from external users
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    uses: codemeistre/.github/.github/workflows/auto_close_issues_and_pull_requests.yml@main
